spring:
    profiles: default
    main:
        bannerMode: "OFF"
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/test?nullNamePatternMatchesAll=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    http:
        encoding.charset: UTF-8
        encoding.enable: true
        encoding.force: true

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: org.jks.mapper.model

#mapper:
#    mappers:
#        - tk.mybatis.springboot.util.MyMapper
#    not-empty: false
#    identity: MYSQL

logging:
    level:
       com.ibatis:DEBUG
server:
  port: 8888
liquibase:
  url: ${spring.datasource.url}
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}
  change-log: classpath:/db/changelog/master.xml


#flyway:
#  locations: classpath:db/migration
#  url: ${spring.datasource.url}
#  user: ${spring.datasource.username}
#  password: ${spring.datasource.password}
#  sql-migration-prefix: V
#  sql-migration-suffix: .sql
#  enabled: true
#  check-location: true
#  baseline-version: 1
#  baseline-on-migrate: true
